-- Consolidated schema snapshot for bootstrapping a new database.
--
-- This is NOT a migration and is not applied by `supabase db push` — it's
-- a convenience file reflecting the current final structure, generated by
-- hand from the live database (this environment has no Docker, so the
-- usual `supabase db dump --schema public` couldn't run). The real source
-- of truth for the live project remains supabase/migrations/*.sql, applied
-- in order; do not delete or renumber those, since Supabase tracks what's
-- applied by migration filename.
--
-- To bootstrap a brand-new project instead of replaying every migration
-- (including now-superseded ones like the old contexts/family_members/
-- groups tables), run this file directly against a fresh database.
--
-- Regenerate after schema changes: query information_schema.columns,
-- pg_constraint, pg_indexes, pg_get_functiondef, pg_get_triggerdef, and
-- pg_policies for the public schema (see the migration history for the
-- exact queries used), or once Docker is available, prefer
-- `supabase db dump --schema public` for an authoritative pg_dump-based
-- version instead of maintaining this by hand.

-- ============================================================
-- Helper function (used by every table's updated_at trigger)
-- ============================================================

create function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================
-- locations
-- ============================================================

create table locations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  name text not null check (char_length(name) > 0),
  latitude double precision,
  longitude double precision,
  radius_m integer check (radius_m > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index locations_owner_id_idx on locations (owner_id);

alter table locations enable row level security;

create policy "Users can view their own locations"
  on locations for select
  using (auth.uid() = owner_id);

create policy "Users can insert their own locations"
  on locations for insert
  with check (auth.uid() = owner_id);

create policy "Users can update their own locations"
  on locations for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "Users can delete their own locations"
  on locations for delete
  using (auth.uid() = owner_id);

create trigger locations_set_updated_at
  before update on locations
  for each row
  execute function set_updated_at();

-- ============================================================
-- rooms (nested under a location)
-- ============================================================

create table rooms (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  location_id uuid not null references locations (id) on delete cascade,
  name text not null check (char_length(name) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index rooms_location_id_idx on rooms (location_id);

alter table rooms enable row level security;

create policy "Users can view their own rooms"
  on rooms for select
  using (auth.uid() = owner_id);

create policy "Users can insert their own rooms"
  on rooms for insert
  with check (auth.uid() = owner_id);

create policy "Users can update their own rooms"
  on rooms for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "Users can delete their own rooms"
  on rooms for delete
  using (auth.uid() = owner_id);

create trigger rooms_set_updated_at
  before update on rooms
  for each row
  execute function set_updated_at();

-- ============================================================
-- owners: individuals and groups, unified. is_individual = true means
-- a real person (may have auth_user_id once they have a login);
-- is_individual = false means a group, which can never authenticate.
-- ============================================================

create table owners (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  auth_user_id uuid references auth.users (id) on delete set null,
  name text not null check (char_length(name) > 0),
  is_individual boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (creator_id, name),
  check (auth_user_id is null or is_individual)
);

alter table owners enable row level security;

create policy "Authenticated users can view the owners directory"
  on owners for select
  using (auth.uid() is not null);

create policy "Users can manage their own owner rows"
  on owners for insert
  with check (auth.uid() = creator_id);

create policy "Users can update their own owner rows"
  on owners for update
  using (auth.uid() = creator_id)
  with check (auth.uid() = creator_id);

create policy "Users can delete their own owner rows"
  on owners for delete
  using (auth.uid() = creator_id);

create trigger owners_set_updated_at
  before update on owners
  for each row
  execute function set_updated_at();

-- ============================================================
-- owner_visibility: "viewer_id can see visible_owner_id" grants.
-- Extends reminders visibility to whole groups, not just direct owners.
-- ============================================================

create table owner_visibility (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  viewer_id uuid not null references owners (id) on delete cascade,
  visible_owner_id uuid not null references owners (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (viewer_id, visible_owner_id)
);

alter table owner_visibility enable row level security;

-- SECURITY DEFINER helpers used across owners/owner_visibility/reminders
-- policies: they need to resolve visibility regardless of who manages the
-- rows involved, not just what the caller's own RLS on those tables would
-- show them directly. Both are narrow, read-only checks keyed to the
-- caller's own auth.uid() — re-verify that scoping if their bodies ever
-- get edited.

create function is_own_owner(check_owner_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from owners where id = check_owner_id and auth_user_id = auth.uid()
  );
$$;

create function owner_is_visible(target_owner_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select is_own_owner(target_owner_id)
    or exists (
      select 1
      from owner_visibility ov
      where ov.visible_owner_id = target_owner_id
        and is_own_owner(ov.viewer_id)
    );
$$;

create policy "Users can view relevant visibility grants"
  on owner_visibility for select
  using (auth.uid() = creator_id or is_own_owner(viewer_id));

create policy "Users can manage their own visibility grants"
  on owner_visibility for insert
  with check (auth.uid() = creator_id);

create policy "Users can update their own visibility grants"
  on owner_visibility for update
  using (auth.uid() = creator_id)
  with check (auth.uid() = creator_id);

create policy "Users can delete their own visibility grants"
  on owner_visibility for delete
  using (auth.uid() = creator_id);

-- New reminders default owner_id/assignee_id to the creator's own owners
-- row, so tasks default to "you" without the app needing to know your id.
create function default_owner()
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select id from owners where auth_user_id = auth.uid() limit 1;
$$;

-- ============================================================
-- projects: a simple per-user grouping for reminders, independent of
-- the owners/visibility model (like locations/rooms, tied directly to
-- auth.uid()). A reminder belongs to at most one project; projects have
-- a manually-orderable priority (lower = higher priority, shown first).
-- ============================================================

create table projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  name text not null check (char_length(name) > 0),
  priority integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, name)
);

create index projects_owner_id_idx on projects (owner_id);
create index projects_priority_idx on projects (priority);

alter table projects enable row level security;

create policy "Users can view their own projects"
  on projects for select
  using (auth.uid() = owner_id);

create policy "Users can insert their own projects"
  on projects for insert
  with check (auth.uid() = owner_id);

create policy "Users can update their own projects"
  on projects for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "Users can delete their own projects"
  on projects for delete
  using (auth.uid() = owner_id);

create trigger projects_set_updated_at
  before update on projects
  for each row
  execute function set_updated_at();

-- New projects append to the end of priority order by default.
create function next_project_priority()
returns integer
language sql
stable
as $$
  select coalesce(max(priority), -1) + 1 from projects where owner_id = auth.uid();
$$;

alter table projects alter column priority set default next_project_priority();

-- ============================================================
-- reminders
-- ============================================================

create table reminders (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references owners (id) default default_owner(),
  title text not null check (char_length(title) > 0),
  notes text,
  due_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  location_id uuid references locations (id) on delete set null,
  recurrence_freq text check (recurrence_freq in ('daily', 'weekly', 'monthly')),
  recurrence_weekday smallint check (recurrence_weekday between 0 and 6),
  room_id uuid references rooms (id) on delete set null,
  assignee_id uuid not null references owners (id) default default_owner(),
  project_id uuid references projects (id) on delete set null,
  constraint reminders_recurrence_weekday_requires_weekly
    check (recurrence_weekday is null or recurrence_freq = 'weekly')
);

create index reminders_owner_id_idx on reminders (owner_id);
create index reminders_assignee_id_idx on reminders (assignee_id);
create index reminders_location_id_idx on reminders (location_id);
create index reminders_room_id_idx on reminders (room_id);
create index reminders_project_id_idx on reminders (project_id);
create index reminders_due_at_idx on reminders (due_at) where completed_at is null;

alter table reminders enable row level security;

create trigger reminders_set_updated_at
  before update on reminders
  for each row
  execute function set_updated_at();

-- Delegation is individual-only; CHECK constraints can't do cross-table
-- lookups, so this needs a trigger.
create function check_assignee_is_individual()
returns trigger
language plpgsql
as $$
begin
  if not exists (select 1 from owners where id = new.assignee_id and is_individual) then
    raise exception 'assignee_id must reference an individual owner (is_individual = true)';
  end if;
  return new;
end;
$$;

create trigger reminders_check_assignee
  before insert or update of assignee_id on reminders
  for each row
  execute function check_assignee_is_individual();

-- Permissions are unified: if you can see an owner (you are it, or hold a
-- visibility grant onto it), you have full SELECT/INSERT/UPDATE/DELETE on
-- anything it owns. No separate "can view but not delete" tier.

create policy "Owners can access visible reminders"
  on reminders for select
  using (owner_is_visible(owner_id));

create policy "Owners can insert reminders they can see"
  on reminders for insert
  with check (owner_is_visible(owner_id));

create policy "Owners can update visible reminders"
  on reminders for update
  using (owner_is_visible(owner_id))
  with check (owner_is_visible(owner_id));

create policy "Owners can delete visible reminders"
  on reminders for delete
  using (owner_is_visible(owner_id));

-- ============================================================
-- Reassignment RPCs
--
-- A plain UPDATE can never set owner_id/assignee_id to something outside
-- the caller's own visibility, even with an unconditional WITH CHECK:
-- Postgres requires an UPDATE's new row to also pass the table's SELECT
-- policy regardless of WITH CHECK (verified directly against a throwaway
-- table during development — this is genuine Postgres behavior, not a bug
-- in this schema). These SECURITY DEFINER functions check visibility of
-- the *current* reminder (so you still can't touch what you can't see),
-- then perform the write with RLS bypassed, so the new owner/assignee can
-- be anyone in the system.
-- ============================================================

create function reassign_reminder_owner(target_reminder_id uuid, new_owner_id uuid)
returns reminders
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  result reminders;
begin
  if not exists (
    select 1 from reminders r where r.id = target_reminder_id and owner_is_visible(r.owner_id)
  ) then
    raise exception 'reminder not found or not visible';
  end if;

  update reminders set owner_id = new_owner_id where id = target_reminder_id
  returning * into result;

  return result;
end;
$$;

create function reassign_reminder_assignee(target_reminder_id uuid, new_assignee_id uuid)
returns reminders
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  result reminders;
begin
  if not exists (
    select 1 from reminders r where r.id = target_reminder_id and owner_is_visible(r.owner_id)
  ) then
    raise exception 'reminder not found or not visible';
  end if;

  if not exists (select 1 from owners where id = new_assignee_id and is_individual) then
    raise exception 'assignee_id must reference an individual owner (is_individual = true)';
  end if;

  update reminders set assignee_id = new_assignee_id where id = target_reminder_id
  returning * into result;

  return result;
end;
$$;

-- Only authenticated callers should be able to attempt reassignment at all
-- (the functions' own visibility checks would reject anon/unauthenticated
-- calls anyway, since auth.uid() is null, but don't rely on that alone).
revoke execute on function reassign_reminder_owner(uuid, uuid) from public;
revoke execute on function reassign_reminder_assignee(uuid, uuid) from public;
revoke execute on function reassign_reminder_owner(uuid, uuid) from anon;
revoke execute on function reassign_reminder_assignee(uuid, uuid) from anon;
grant execute on function reassign_reminder_owner(uuid, uuid) to authenticated;
grant execute on function reassign_reminder_assignee(uuid, uuid) to authenticated;
